export type UiLanguage = 'en' | 'zh-CN';

export function isUiLanguage(value: unknown): value is UiLanguage {
  return value === 'en' || value === 'zh-CN';
}

export const chineseUi: Record<string, string> = {
  'Start delivery': '开始交付',
  'Brief confirmed. Click Start delivery to begin implementation.':
    '交付简报已确认。点击“开始交付”后，将启动 Agent 执行。',
  'Resolve {count} open decisions in the composer before confirming.':
    '还有 {count} 项待决定，请先在右下角回复，再确认简报。',
  'View task document': '查看任务文档',
  'Delivery withdrawn': '本次交付已撤销',
  'This unaccepted attempt was withdrawn. Prepare a new brief; the next execution will start from latest main. Previously merged code is unchanged.':
    '本次未验收交付已撤销。可以重新准备交付简报，下一次执行将从最新 main 开始；已合并代码不受影响。',
  'Withdraw delivery': '撤销本次交付',
  'Withdraw this unaccepted delivery? Running work will stop, unaccepted workspace changes will be discarded, and any open delivery PR will be closed. Other targets and merged code are unchanged.':
    '撤销本次未验收交付？正在运行的任务会先停止，当前工作区的未验收改动会被丢弃，已有未合并 PR 会被关闭。其他任务和已合并代码不受影响。',
  'Orchestrator model': 'Orchestrator 编排模型',
  'Understands the target, delegates tasks and brings the delivery together.':
    '负责理解目标、分配任务和汇总交付。',
  'Remove model': '移除模型',
  'Undelivered targets: {count}': '未交付节点：{count}',
  Models: '模型',
  You: '你',
  'Independent review not needed': '无需独立审查',
  'Review approved': '审查已通过',
  'Review pending': '等待审查',
  'Confirm existing delivery': '确认已有交付',
  'Development Delivery instructions': '开发交付指令',
  'Prepare delivery brief': '准备交付简报',
  'Continue delivery': '继续交付',
  'Development Delivery': '开发交付',
  'Delivery Contracts': '交付 Contract',
  'Ready to deliver': '可准备交付',
  'Preparing delivery brief': '正在准备交付简报',
  'In review': '审查中',
  'Waiting for feedback': '等待反馈',
  'Delivery settings': '交付设置',
  'Worker models': 'Worker 模型池',
  'Reviewer models': 'Reviewer 模型池',
  'Add model': '添加模型',
  'Delivery brief': '交付简报',
  'Confirm delivery brief': '确认交付简报',
  'Delivery feedback': '交付反馈',
  'Discuss delivery': '讨论交付目标',
  'Accepted executable targets appear here automatically.':
    '正式接受的可执行目标会自动出现在这里。',
  'Prepare this target with your selected models.':
    '使用所选模型准备这个交付目标。',
  'Describe the outcome or your feedback.': '描述交付目标或你的反馈。',
  'Accept this delivery and merge its pull request?':
    '确认验收本次交付并合并对应 PR？',
  'Accept and merge': '验收并合并',
  'Target is no longer available.': '此目标已不再可用。',
  'Product Discovery & Design': '产品探索与设计',
  'Product Discovery & Design instructions': '产品探索与设计指令',
  'Delivery Planning instructions': '交付规划指令',
  'Applies to new Delivery Planning requests. Running requests keep their original instructions. Leave blank to use only the Harness defaults.':
    '适用于新的交付规划请求。正在运行的请求继续使用原有指令；留空则只使用系统默认规则。',
  'Scope Decomposition': '范围分解',
  'Scope Decomposition canvas': '范围分解画布',
  'Scope Decomposition workspace': '范围分解工作区',
  'Domain Modeling': '领域建模',
  'Delivery Planning': '交付规划',
  Implementation: '开发执行',
  'Open in Delivery Planning': '在交付规划中打开',
  'Open in Implementation': '在开发执行中打开',
  "What's That?": '这是什么？',
  "What's Next instructions": 'What’s Next 全局 Instructions',
  'Explore the next supported product direction.':
    '探索产品接下来值得推进的方向。',
  'Domain Model instructions': '领域模型指令',
  'Applies to new Domain Model requests. Running requests keep their original instructions. Leave blank to use only the Harness defaults.':
    '保存后对新的 Domain Model 请求生效，不改变正在运行的请求。留空则只使用 Harness 默认规则。',
  'Define the entities, fields and relationships behind the product.':
    '定义产品中的实体、字段与关系。',
  'Module instructions': '指令',
  Undone: '已撤销',
  'The last model change was undone.': '上一次领域模型修改已撤销。',
  'Preparing the Agent request.': '正在准备 Agent 请求。',
  'Generating the Domain Model.': '正在生成领域模型。',
  'Describe the model change': '描述模型修改',
  'Describe an entity, field, relationship or rule to add or change.':
    '描述要添加或修改的实体、字段、关系或规则。',
  'Describe an entity, field, relationship or rule to add or change…':
    '描述要添加或修改的实体、字段、关系或规则…',
  '{count} selected model entries will be treated as primary context.':
    '已选择 {count} 个模型条目作为主要上下文。',
  'Clear context': '清除上下文',
  'Domain Model Agent': '领域模型 Agent',
  Added: '新增',
  'Updated entries': '更新',
  Removed: '移除',
  Cards: 'Card',
  Rules: '规则',
  Card: 'Card',
  Field: '字段',
  Constraint: '规则',
  'Model changes': '模型变更',
  'Run activity': '运行记录',
  'Model entry no longer present': '已不在当前模型中的条目',
  '{cards} Cards · {entries} model entries':
    '{cards} 张 Card · {entries} 个模型条目',
  'One to one': '一对一',
  'One to many': '一对多',
  'Many to one': '多对一',
  'Many to many': '多对多',
  'Undo last change': '撤销上次修改',
  'Primary fields': '主要字段',
  'Other fields · {count}': '其他字段 · {count}',
  Relationship: '关系',
  Constraints: '约束',
  'Discuss this {kind}': '讨论此{kind}',
  Entity: '实体',
  explicit: '明确',
  inferred: '推断',
  derived: '派生',
  inheritance: '继承',
  containment: '包含',
  association: '关联',
  'Add {name} to context': '将{name}添加到上下文',
  'Remove {name} from context': '将{name}从上下文移除',
  'Open {name} details': '打开{name}详情',
  '{count} fields': '{count} 个字段',
  'The current Domain Model was updated.': '当前领域模型已更新。',
  'The Domain Model Agent failed.': '领域模型 Agent 运行失败。',
  'The Agent Run was canceled. The Domain Model was not changed.':
    'Agent 运行已取消，领域模型没有改变。',
  'A Domain Model User Input is required.': '请输入领域模型修改要求。',
  'Select no more than 20 Domain elements.': '最多选择 20 个领域模型元素。',
  'Select no more than 50 Context documents.': '最多选择 50 份上下文文档。',
  'Attach no more than 20 Markdown files.': '最多添加 20 个 Markdown 文件。',
  'A Domain Model Agent Run is already active.':
    '已有领域模型 Agent 正在运行。',
  'A selected Domain element is no longer available.':
    '选中的领域模型元素已不可用。',
  'The Domain Model Run is not active.': '领域模型运行当前未在进行。',
  'The Domain Model Run is already finishing.': '领域模型运行正在结束。',
  'Invalid Domain Model Run.': '无效的领域模型运行。',
  'The Agent Run was interrupted. The Domain Model was not changed.':
    'Agent 运行被中断，领域模型没有改变。',
  'Only Markdown files can be attached to a Domain Model Run.':
    '领域模型运行只能添加 Markdown 文件。',
  'Each Domain Model attachment must be 2 MB or smaller.':
    '每个领域模型附件不能超过 2 MB。',
  'Domain Model Context must remain inside the project.':
    '领域模型上下文必须位于项目目录内。',
  'The Domain Model changed while the Agent was running.':
    'Agent 运行期间领域模型已发生变化。',
  'There is no Domain Model change to undo.': '没有可以撤销的领域模型修改。',
  'Could not start the Domain Model Agent.': '无法启动领域模型 Agent。',
  'Could not undo the last change.': '无法撤销上次修改。',
  'Could not refresh the Domain Model.': '无法刷新领域模型。',
  'Could not cancel the Domain Model Agent.': '无法取消领域模型 Agent。',
  'No recorded activity.': '没有活动记录。',
  'Open project location': '在本地路径打开',
  'Could not open project location.': '无法打开本地路径。',
  'Applies to the next request, including continued sessions. Running requests keep their original instructions. Leave blank to use only the Harness defaults.':
    '保存后对下一轮请求生效，包括续接会话；不改变正在运行的请求。留空则只使用 Harness 默认规则。',
  'Optional language, collaboration preferences, or project constraints.':
    '可填写语言、协作偏好或项目约束；也可以留空。',
  'Saved. The next request will use these Instructions.':
    '已保存，下一轮请求将使用这些 Instructions。',
  'Could not load Instructions.': '无法加载 Instructions。',
  'Could not save Instructions.': '无法保存 Instructions。',
  'Choose a goal to add. Added Cards are shown for context only.':
    '选择未加入的目标；已加入卡片仅作结构参考，不可再次选择。',
  'Not started': '未开始',
  'Already added': '已加入',
  Waiting: '等待前置项',
  'Waiting for prerequisites': '等待前置项',
  'Open goal': '打开目标',
  'Goal map': '任务框架',
  'Goal source': '目标来源',
  'Prerequisite → dependent': '执行依赖：前置 → 后续',
  'Decomposition / origin · not execution order':
    '分解／来源关系 · 不代表执行顺序',
  'Click a Card to add it or open its existing Plan.':
    '点击卡片添加目标；已加入的会打开已有计划。',
  'No unfinished formal Nodes in this module.':
    '这个模块还没有未完成的正式节点。',
  'Choose your next goal from the task map. Prerequisites are on the left; dependent work follows on the right.':
    '从任务框架中选择接下来要做的事。前置任务在左，依赖它的任务在右。',
  'Some dependencies form a cycle; execution order cannot be inferred.':
    '部分依赖形成了循环，无法确定执行顺序。',
  'Some prerequisites are outside this view. Adding a goal does not execute it.':
    '部分前置节点不在当前视图中。添加目标不会开始执行。',
  'Send to Agent': '发送给 Agent',
  'Planning only': '仅规划',
  'Agent running': 'Agent 运行中',
  Loading: '加载中',
  'Live planning · read-only Agent · execution not connected':
    '真实规划 · Agent 只读 · 执行尚未接入',
  'Add a formal Node, then plan with your Agent.':
    '添加正式节点，与 Agent 一起制定执行计划。',
  'No goals yet. Add a formal Node to start planning.':
    '还没有目标。添加正式节点后开始规划。',
  'Plan finalized': '计划已确认',
  Planning: '规划中',
  'Not planned yet': '尚未规划',
  'Execution not connected': '执行尚未接入',
  'Working instructions': '工作指令',
  'Custom instructions (optional)': '自定义工作指令（可选）',
  'Applies to every Implementation Card in this project. System workflow rules are built in; only add your own preferences here. Changes apply to new planning runs, not running Agents.':
    '适用于当前项目的所有开发执行任务卡。系统流程规则已内置，只需填写你的补充要求。修改将在新规划中生效，不影响运行中的 Agent。',
  'Add development conventions or local Skill instructions. Leave empty to use the built-in workflow.':
    '填写开发约定、使用哪些本地 Skill 等。可以留空，系统会自动应用内置流程规则。',
  'Your additional requirements': '你的补充要求',
  'Original input': '原输入',
  'Dependency review required': '需要确认依赖关系',
  'This Card derives from unfinished Nodes that were not marked as prerequisites. Classify each one before planning or confirming this Card.':
    '这张卡片来源于尚未完成、但未标记为前置依赖的节点。开始或确认计划前，请逐项确认它们的关系。',
  'Conceptual source only': '仅作为概念来源',
  'Add as prerequisite': '添加为前置依赖',
  'Delete this Card': '删除这张卡片',
  'Delete this Card?': '删除这张卡片？',
  'The Implementation Card and its unconfirmed draft will move to system Trash. Its upstream source remains unchanged.':
    '开发执行卡片和未确认的计划草稿会移到系统废纸篓，上游来源保持不变。',
  'Move Card to Trash': '移到废纸篓',
  'Model ID (optional)': '模型 ID（可选）',
  'Agent configuration': 'Agent 配置',
  'Plan together, execute one Action, then verify the output.':
    '一起制定计划，逐步执行，再验收产出。',
  'Completed Actions': '已验收步骤',
  Actions: '执行步骤',
  'Local Git baseline': '本地 Git 基线',
  'App-owned history; separate from repository commits and PRs.':
    '应用内部版本记录，与工程 Commit／PR 分开。',
  'Local version': '本地版本',
  'View version diff': '查看版本差异',
  'Plan editing is locked after execution starts. Rollback is not connected yet.':
    '执行开始后不可直接修改计划；干净回退功能暂未接入。',
  'Select the current Action to start. Later Actions unlock after acceptance.':
    '选择当前步骤开始执行，验收后解锁下一步。',
  'Refresh GitHub status': '刷新 GitHub 状态',
  'Last attempted check': '最近查询时间',
  'Stale status': '历史状态',
  OPEN: '未合并',
  CLOSED: '已关闭',
  MERGED: '已合并',
  'No verified PR association for this output.': '尚未核实此产出关联的 PR。',
  'PR state is separate from your acceptance. Refresh to check for remote changes.':
    'PR 状态与用户验收分开记录；点击刷新查询远端变化。',
  'No GitHub repository was captured for this round. Future rounds discover it automatically.':
    '本轮未记录 GitHub 仓库，后续执行轮次会自动发现。',
  'Could not refresh GitHub status. Check login and repository access. Previous status is not current verification.':
    '无法刷新 GitHub 状态，请检查登录和仓库权限。历史状态不代表当前核验结果。',
  'Could not capture repository output. No GitHub delivery was verified.':
    '无法记录仓库产出，尚未核实 GitHub 交付。',
  'Starting runs the Agent with project write access. Only this Action runs; you decide acceptance. GitHub status never starts the next Action.':
    '开始后 Agent 可以修改项目文件，只执行当前步骤，由你验收。GitHub 状态不会自动启动下一步。',
  'Output evidence could not be verified. The Agent report is retained below.':
    '产出证据未通过核验。下方保留了 Agent 的报告。',
  'Evidence validation details': '证据校验详情',
  'Unverified check references': '未核实的自检引用',
  'These references were reported by the Agent; the host has not verified the commands or external results.':
    '以下引用由 Agent 报告，系统尚未核实命令执行或外部结果。',
  'Card workspace': 'Card 工作区',
  Branch: '分支',
  'Previous workspace backup': '上一次工作区备份',
  'Base commit': '起点提交',
  'All Actions use this worktree. Main changes only through the agreed PR delivery flow.':
    '所有步骤共用这个 worktree，main 只通过约定的 PR 交付流程接收成果。',
  'Restart this Card from its base': '让这张 Card 从头开始',
  'Keep the confirmed Plan. Preserve this worktree and branch as a backup, then create a fresh Card worktree at its original base. No Action starts automatically.':
    '保留已确认计划，将当前 worktree 和分支完整保留为备份，再从最初的起点创建新工作区。不会自动开始执行。',
  'Main, GitHub repositories, PRs and installed apps are not reverted by this operation.':
    '此操作不会回退 main、GitHub 仓库、PR 或已安装应用。',
  'Back up and restart Card workspace': '备份并重建 Card 工作区',
  'Roll back': '回退',
  'Return to planning?': '回退到计划？',
  'Back up the current workspace, restore the Card baseline, clear accepted Actions, and reopen the Plan.':
    '备份当前工作区，恢复 Card 起点，清除已验收步骤，并重新打开计划。',
  'Confirm roll back': '确认回退',
  'Working…': '处理中…',
  'Execution permissions': '执行权限',
  'full-access': '完全访问',
  'workspace-write': '工作区写入',
  'read-only': '只读',
  'Codex execution follows your local Full Access or read-only choice. Full Access relies on worktree and PR discipline, not an OS write barrier around main.':
    'Codex 执行会遵循你本地的完全访问或只读选择。完全访问依靠 worktree 和 PR 流程约束，不再由操作系统禁止写入 main。',
  'Recheck saved report without rerunning Agent':
    '重新核验已保存报告（不重跑 Agent）',
  'This Action was accepted by you.': '你已验收这一步的产出。',
  'Accept earlier Actions before starting this step.':
    '请先验收前面的步骤，再开始这一步。',
  'Your input': '你的输入',
  'Historical checks (not classified)': '历史检查（未分类）',
  'Confirmed checklist locked': '已确认清单已锁定',
  'Plan and acceptance criteria are locked after confirmation. User decisions remain separate.':
    '计划与验收标准确认后锁定，用户裁决单独记录。',
  'Current status': '当前状态',
  'No PR': '暂无 PR',
  'Open workspace folder': '打开工作区',
  'Workspace path': '路径',
  'Shared by this Card’s Actions. Main receives changes through PR merges.':
    '所有步骤共用此工作区；通过 PR 合并到 main。',
  'App bundle verification is not supported yet.':
    '系统暂不支持 .app 构建目录核验；需补齐支持后处理，重复核验无法解决。',
  'Acceptance is unavailable until the system artifact verification is resolved.':
    '系统产物核验尚未解决，暂不能确认验收。',
  'This run has not produced a verified output for acceptance.':
    '本轮尚无可确认验收的已核验产出。',
  'Required checks are incomplete. Review them before confirming acceptance.':
    '必查项尚未全部通过，请先查看具体结果。',
  'System artifact verification note': '系统产物核验提示',
  'Artifact verification notes do not block acceptance when required checks pass.':
    '此项为系统核验提示；必查项通过即可验收。',
  Feedback: '反馈',
  'Cancel changes': '取消修改',
  'Confirm changes': '确认修改',
  'Enter change instructions': '填写修改意见',
  'Run information': '运行信息',
  'Run started': '开始时间',
  'System diagnostics': '系统诊断',
  'Verification note': '有核验提示',
  'Execution settings': '执行设置',
  'Applies to the next execution, not the recorded round.':
    '用于后续执行，不影响已记录的轮次。',
  'Retry verification': '重试核验',
  'System artifact verification pending': '系统产物待核验',
  'Agent-reported required checks': 'Agent 必查结果',
  'The system has not verified these delivery references:':
    '系统尚未核验以下交付物：',
  'Resolve artifact verification before acceptance. Additional checks do not cause this state.':
    '处理产物核验后才能验收；此状态并非由附加项造成。',
  'Current Action gaps': '当前步骤尚未完成',
  'Stop execution': '停止执行',
  'Stop execution?': '停止本轮执行？',
  'Stopping keeps the current code and files. It does not restore an earlier version.':
    '停止后保留当前代码和文件，不会恢复到之前的版本。',
  'To restart from the original baseline, use the separate Card restart action when available; it creates a backup first.':
    '如需从初始版本重新开始，请使用单独的 Card 重开操作（适用时会先备份）。',
  'Keep running': '继续运行',
  Undo: '撤销',
  'Undo this Action?': '撤销这一步？',
  'Return this Action to its clean starting point. Previous passed Actions and the Plan stay unchanged.':
    '恢复到这一步开始前。已通过的步骤和计划保持不变。',
  'Execution phase': '执行',
  'Acceptance phase': '验收',
  'Confirm Action acceptance': '确认验收这一步',
  'Review this output, required checks and any user overrides before confirming.':
    '请确认本轮产出、必查结果和用户裁决。',
  'Code revision': '代码版本',
  'Not recorded': '未记录',
  'These are Agent-reported results. Passing self-checks does not replace your review.':
    '以上是 Agent 报告的检查结果，自检通过不代替你的审阅。',
  'Acceptance unlocks the next Action': '确认后解锁下一步',
  'This is the final Action in this Plan.': '这是本计划的最后一步。',
  'Nothing starts automatically. Acceptance does not merge a PR.':
    '不会自动开始执行，也不会合并 PR。',
  'Output changed. Close this dialog and review the latest output before confirming.':
    '产出已变化，请关闭弹窗并重新查看最新结果后确认。',
  'Back to review': '返回查看',
  'Confirm acceptance': '确认验收通过',
  'Elapsed time': '总耗时',
  'Current activity': '当前活动',
  'Last update': '最近更新',
  ago: '前',
  'Preparing coordinated execution.': '协调 Agent 正在准备任务。',
  'Confirm this user decision': '确认此项用户裁决',
  'Coordinator report': '协调 Agent 整理结果',
  'Agent self-check': '执行 Agent 自检结果',
  'Coordination record': '协调记录',
  calls: '次调用',
  Coordinator: '协调 Agent',
  Worker: '执行 Agent',
  'Coordination profile': '协调配置',
  'Usage not available': '尚无用量记录',
  'View recorded response': '查看原始报告',
  'View activity log': '查看活动记录',
  'Current Action': '当前推进步骤',
  'Current stage': '当前',
  'Required checks': '必查项',
  'Additional checks': '附加项',
  'Pass condition': '通过条件',
  Evidence: '验收证据',
  'Observed result': '实际检查结果',
  'Passed by user decision': '用户裁决通过',
  'Use feedback as user decision to pass this item':
    '用当前反馈明确裁决此项通过',
  'No fixed checklist. Define it before execution.':
    '尚无固定验收清单，请在执行前补齐。',
  'Historical report without a fixed checklist; rerun against confirmed criteria.':
    '本历史轮次没有固定清单，不能据此判定新清单通过。',
  'Agent-reported checks': 'Agent 自检结果',
  'Remaining work': '尚未完成',
  'Observed file and Git changes': '已检测到的文件与 Git 变更',
  'Self-checks are not acceptance. Canceling does not revert changes.':
    '自检不等于验收；取消不会撤销已产生的变更。',
  'Feedback for this Action': '针对这一步的反馈',
  'Additional Action instructions': '这一步的补充要求',
  'Add requirements for this step, or leave empty to follow the confirmed Plan.':
    '补充这一步的要求，也可以留空，按已确认计划执行。',
  'Starting runs the Agent with project write access. Only this Action runs; you decide acceptance. GitHub merge is not monitored yet.':
    '开始后 Agent 可以修改项目文件，只执行当前步骤，由你验收。暂不自动同步 GitHub 合并状态。',
  'Claude can edit project files; commands requiring approval may return blocked in this non-interactive run.':
    'Claude 可以编辑项目文件；需要额外批准的命令可能返回阻塞说明。',
  'Continue this Action': '继续修改这一步',
  'Start this Action': '开始执行这一步',
  'Accept this output': '验收当前产出',
  'Modify or clarify': '修改或澄清',
  Redo: '重做',
  Pass: '通过',
  passed: '通过',
  failed: '失败',
  'not-run': '未执行',
  'Custom model…': '自定义模型…',
  'Custom model ID': '自定义模型 ID',
  'Previously selected': '此前选择',
  'Loading local models…': '正在读取本地模型…',
  'Could not load models. Use Agent default or enter a custom model.':
    '未能读取模型。可以使用 Agent 默认模型，或手动填写。',
  'No models returned. Use Agent default or enter a custom model.':
    '本地 Agent 未返回模型。可以使用默认模型，或手动填写。',
  'Models reported by your local Agent. Availability is checked when running.':
    '模型列表来自本地 Agent，实际可用性以运行结果为准。',
  'Agent default': 'Agent 默认',
  Default: '默认',
  'Could not load models. Use Default or enter a custom model.':
    '未能读取模型。可以使用默认模型，或手动填写。',
  'No models returned. Use Default or enter a custom model.':
    '本地 Agent 未返回模型。可以使用默认模型，或手动填写。',
  'Could not load models. Retry or enter a custom model.':
    '未能读取模型。请重试或手动填写模型。',
  'No models returned. Enter a custom model.':
    '本地 Agent 未返回模型，请手动填写。',
  'Uses your local Agent login. Unsupported model settings return an error, without silently changing models.':
    '使用本地 Agent 登录。模型配置不受支持时会报错，不会悄悄换模型。',
  'Actions are ready. Execution is not connected yet.':
    '执行步骤已就绪；暂未接入代码执行。',
  'Reopen plan': '重新调整计划',
  'Last run usage': '上轮用量',
  'Choose a formal Node. Its output is retained for planning; the source is unchanged.':
    '选择一个正式节点。保留其产出用于规划，不修改来源节点。',
  'No formal Nodes available yet.': '还没有可导入的正式节点。',
  'Prerequisites not yet verified': '前置成果尚未验收',
  'Could not load planning.': '无法加载规划工作区。',
  'Planning request failed.': '规划请求失败。',
  'Attach no more than five resources.': '最多添加 5 份资料。',
  'Use text or Markdown files up to 256 KB.':
    '请使用不超过 256 KB 的文本或 Markdown 文件。',
  'Preview mode': '预览模式',
  'Open preview': '打开预览',
  'Exit preview': '退出预览',
  'Real planning and execution are not connected yet.':
    '真实规划与执行尚未接入。',
  'Explore the agreed workflow with sample data. No Agent, GitHub, or project writes. Changes reset when you reload or leave preview.':
    '使用示例数据体验已确认的流程，不调用 Agent、不修改 GitHub 或项目。刷新或离开预览后，演示改动会重置。',
  'Follow-up work for a later plan.': '留待后续计划处理的事项。',
  'Demo Issue: GitHub is not connected.': '示例 Issue，尚未连接 GitHub。',
  'Not connected': '未连接',
  'Todo added · demo': '已添加 Todo · 演示',
  'Follow-up recorded': '已加入演示 Todo',
  'Tell the Agent what to remember': '让 Agent 记下一个想法',
  'Describe the later work in your own words. The Agent organizes the Issue and its context. This is a scripted demo; no real GitHub Issue is created.':
    '用自己的话说后续想做什么，由 Agent 整理需求与上下文。当前为预设演示，不创建真实 GitHub Issue。',
  'Organizing your follow-up…': '正在整理后续事项 · 演示…',
  'Original request & context': '原始需求与来源上下文',
  Done: '完成',
  'What should we keep for later?': '有什么想法留到以后？',
  'For example: we may need multi-device login later. Not in this delivery; add it to Todo.':
    '例如：后续可能要加入多端登录支持，这一轮先不做，帮我加到 Todo。',
  'The current goal, Action, and available output are included automatically. Current blockers still belong to this delivery.':
    '自动带入当前目标、步骤与已有产出。本轮阻塞问题仍留在当前交付中解决。',
  'Ask Agent to record it · demo': '交给 Agent 整理 · 演示',
  'From validation': '来自验收',
  'User idea': '临时想法',
  'Optional review follow-up': '可选的后续事项 · 演示',
  'Later, add a cross-platform verification checklist. This is outside the current local-only delivery and does not waive any blocking finding.':
    '后续可补充跨平台验证清单。这不属于本轮本地交付，也不能替代当前阻塞问题的修复。',
  'Ask Agent to add this to Issues': '让 Agent 整理为 Issue',
  'Only this step is updating. You can still browse the plan on the left.':
    '仅更新这一步，你仍可浏览左侧计划。',
  'For example: three steps feel too broad. Could you break them into four?':
    '例如：3 步有点少，可以细化成 4 步吗？',
  'Try the demo: refine three steps into four': '演示可试：把三步细化成四步',
  'Requested step change': '希望这一步怎样调整',
  'Describe the change. You do not need to write the input, output, or validation yourself. This demo retains guidance; real AI integration comes later.':
    '直接说明想改什么，不必自己填写输入、输出和验收。当前演示保留调整要求，真实 AI 后续接入。',
  'Demo library only. Local files stay in this tab; no project library is read or changed.':
    '资料库为示例。本地文件仅在本页保留，不读取或修改真实项目资料库。',
  'Start planning': '开始规划',
  'This goal is here. Nothing has been planned or started yet.':
    '目标已添加，还没有计划，也没有开始执行。',
  'Preparing your plan…': '正在生成计划…',
  'Updating this planned step…': '正在调整这一步…',
  'The start form is put away. Your plan will appear as individual steps when ready.':
    '完成后将按步骤展示计划，你可以逐项查看和调整。',
  'Plan preview': '计划预览 · 待确认',
  'Review each step, then confirm the entire plan to create Actions.':
    '先看概览和步骤，整体确认后再进入执行。',
  'Adjust whole plan': '调整整份计划',
  'Add planned step': '添加步骤',
  'Usually 5–7 steps; fewer is fine. Keep the goal manageable.':
    '通常 5–7 步比较容易把握，简单目标可以更少。',
  'Planned step': '计划步骤',
  'Adjust this step': '调整这一步',
  'Step guidance': '本步补充说明',
  'Plan guidance': '计划补充说明',
  'Included from the source goal': '已带入的目标上下文',
  'Adjustments to the plan': '希望怎样调整',
  'Extra resources': '额外资料',
  'Import planning resources': '导入规划资料',
  'Import files': '导入文件',
  'Optional Markdown or text. Read in this tab only; nothing is uploaded.':
    '可选 Markdown 或文本，仅在本页读取，不上传到服务端。',
  'Use up to 5 Markdown or text files, at most 256 KB each.':
    '最多添加 5 个 Markdown 或文本文件，每个不超过 256 KB。',
  'Extra resources must total at most 1 MB.': '额外资料合计不超过 1 MB。',
  'Could not import these resources. Keep the total below 1 MB.':
    '无法导入这些资料，请使用文本文件并将总量控制在 1 MB 以内。',
  'Remove resource {name}': '移除资料 {name}',
  'Start Plan · demo': '开始规划 · 演示',
  'Update plan · demo': '更新计划 · 演示',
  'Update step · demo': '更新这一步 · 演示',
  'Scripted demo: adjustments replace the current draft. No planning history or Git versions are kept.':
    '预设演示：调整只更新当前草案，规划阶段不保留历史或 Git 版本。',
  'Edit this step in place. Other steps stay unchanged; confirmation still applies to the whole plan.':
    '只调整这一步的边界，其他步骤保持不变；最终仍需确认整份计划。',
  'Save step changes': '保存本步调整',
  'Add to plan preview': '加入计划预览',
  "This plan's scope": '本轮范围',
  'Scan the titles on the left. Open a step only when you need its input, output, and validation details.':
    '先扫一眼左侧标题；需要了解细节时，再点开某一步查看输入、产出和验收。',
  'Prerequisite deliveries': '前置成果',
  Model: '模型',
  'Provider default': '沿用默认配置',
  'Reasoning model · demo': '推理模型 · 演示',
  'Lightweight model · demo': '轻量模型 · 演示',
  'Reasoning effort': '推理强度',
  Provider: '模型提供方',
  'Reset reasoning effort': '重置推理强度',
  none: '无',
  minimal: '最低',
  low: '低',
  medium: '中',
  high: '高',
  xhigh: '极高',
  max: '最大',
  ultra: '超高',
  'Planning profile': '规划配置',
  'Execution profile': '执行配置',
  'Review profile': '审查配置',
  'Requested profile': '本轮请求配置',
  'Demo profiles only, not a live model catalog. Nothing is sent to a provider.':
    '仅演示配置，不是账号真实模型列表，也不会发送给服务商。',
  'Plan the whole goal': '先规划整个目标',
  'Discuss and revise the complete plan. Actions appear only after you accept the whole plan.':
    '先讨论和调整整份计划，整体确认后才展开执行步骤。',
  'Feedback on the whole plan': '对整份计划的反馈',
  'Simulate plan revision': '模拟调整计划',
  'Simulate Generate Plan': '模拟生成计划',
  'Demo plan result': '演示结果',
  'Standard example': '标准示例',
  'Shorter example': '精简示例',
  'This is a scripted planning demo, not AI. Feedback is retained; edit the proposed contracts directly to explore changes.':
    '这是预设交互演示，不是真实 AI。反馈会被保留；可以直接修改步骤约定来体验调整。',
  'Preparing a plan draft…': '正在准备计划草案…',
  'Plan generation failed. Your input and earlier draft are retained; retry before confirming.':
    '生成计划失败，输入和此前草案保留。请重试后再确认。',
  'Plan generation canceled. No Actions were created.':
    '已取消生成，本轮没有创建新的执行步骤。',
  'Planning response': '规划回应',
  'Plan response version': '规划回应版本',
  'Historical response only. Return to the latest version to confirm the current draft.':
    '正在阅读历史回应；请回到最新版本再确认当前草案。',
  'Current plan draft': '当前计划草案',
  'Plan steps': '个计划步骤',
  'Aim for roughly 5–7 meaningful steps, not a quota. Simple goals need fewer. These exact contracts become Actions when confirmed.':
    '通常 5–7 步比较容易把握，但不凑数，简单目标可以更少。确认后，下面这些约定直接成为执行步骤。',
  'This plan may be too large. Consider reducing the goal instead of hiding complexity inside steps.':
    '计划可能过大，建议缩小本轮目标，而不是把复杂工作硬塞进少数步骤。',
  'Existing delivery retained': '保留已有交付',
  'Step title': '步骤标题',
  'Confirm entire plan': '确认整份计划',
  'No Actions yet. Confirm the entire plan first.':
    '尚无执行步骤。先生成、讨论并确认整份计划。',
  'Working directory': '工作目录',
  'Prepare a follow-up Issue': '准备后续 Issue',
  'Only defer out-of-scope work. Current delivery blockers must stay in this Action. No GitHub Issue will actually be created.':
    '只记录范围外的新需求。本轮阻塞问题仍须在当前步骤解决。这里不会创建真实 GitHub Issue。',
  'Issue title': 'Issue 标题',
  'Why later?': '为什么留到以后？',
  'Expected future outcome': '后续预期成果',
  'Simulate creating Issue': '模拟创建 Issue',
  'New follow-up': '记个想法',
  'GitHub Issues will own these Todos. This preview only simulates Issue metadata and open/closed state.':
    '后续以 GitHub Issues 管理待办。本页仅模拟 Issue 信息及打开、关闭状态。',
  Open: '未关闭',
  Closed: '已关闭',
  'Sample Issue': '示例 Issue',
  'From action': '来源步骤',
  'Simulate Issue reopened': '模拟重新打开',
  'Simulate Issue closed': '模拟关闭 Issue',
  'Add Todo': '添加 Todo',
  'Plan progress': '计划进度',
  'Completed {done} / {total} steps': '已完成 {done} / {total} 步',
  'Open goal: {title}': '打开目标：{title}',
  'Open source node {id} in a new tab': '在新标签页定位来源节点 {id}',
  'Demo source canvas': '演示来源画布',
  'Located source: {id}': '已定位来源：{id}',
  'Fictional source node. This read-only canvas does not load or change your real graph.':
    '虚构的来源节点。此只读画布不读取或修改真实图数据。',
  Demo: '演示',
  'Interactive demo': '交互演示',
  'Sample data only. No Agent, GitHub, or project writes.':
    '仅示例数据 · 不调用 Agent，不写入 GitHub 或项目',
  'Reset demo': '重置演示',
  'Execution workspace': '执行工作台',
  'Turn a goal into something you can verify. One action at a time.':
    '把想做的事，变成可验收的成果。一步一步来。',
  'Add a goal': '添加目标',
  'All goals': '全部目标',
  'Needs attention': '等你处理',
  'In progress': '进行中',
  Completed: '已完成',
  'Drop files or choose local files': '拖入文件或选择本地文件',
  'GitHub repository or code URL': 'GitHub 仓库或代码链接',
  'Paste a GitHub repository or code URL': '粘贴 GitHub 仓库或代码链接',
  'Use a GitHub repository, directory, file or permalink URL.':
    '请输入 GitHub 仓库、目录、文件或固定版本链接。',
  'Sync Up': '同步',
  'Syncing…': '同步中…',
  'Main sync is already running.': '正在同步 main，请稍候。',
  'The project directory is not a repository root.':
    '项目目录不是 Git 仓库根目录。',
  'Remote default branch is unavailable. Retry before creating a new task.':
    '远端主分支不可用，请重试后再创建任务。',
  'Could not fetch the latest default branch. Retry before creating a new task.':
    '无法获取最新主分支，请重试后再创建任务。',
  'Main synced.': 'main 已同步',
  'Main is already up to date.': 'main 已是最新',
  'Commit or save local changes before syncing main.':
    '请先提交或保存主目录中的改动，再同步 main。',
  'Switch the primary checkout to main before syncing.':
    '请先将项目主目录切换到 main，再同步。',
  'Local main has commits outside origin/main. Sync stopped without changing local files.':
    '本地 main 有远端之外的提交，已停止同步并保留本地文件。',
  'Could not sync main.': '无法同步 main。',
  'Delivery in progress': '交付中',
  'Filter goals': '筛选目标',
  'Search goals': '搜索目标',
  'No goals match this view.': '没有符合条件的目标。',
  'Clear filters': '清除筛选',
  'Try the website goal for a review loop, or explore blocked, failed, deleted-source, and completed examples. Reloading resets this demo.':
    '可以从网站骨架体验审查闭环，也可以试试受阻、失败、来源删除和完成的示例。刷新页面会重置演示。',
  'Add a sample goal': '添加示例目标',
  'This library is fictional. Your real source nodes will not be read or changed.':
    '这是虚构的示例库，不会读取或修改你的真实来源节点。',
  'Open existing goal': '打开已有目标',
  'Add and prepare a plan': '添加并准备计划',
  'Reset this demo?': '重置本次演示？',
  'Only the examples in this tab will be reset. No project files are affected.':
    '仅重置此标签页的示例，不影响任何项目文件。',
  'Verified actions': '已验收步骤',
  'Every action has been verified.': '所有步骤均已验收。',
  'Demo branch': '示例分支',
  'Sample PRs': '示例 PR',
  'Source node deleted': '来源节点已删除',
  'Goal complete. The source stays a Formal Node with an associated completion marker.':
    '目标已完成。来源仍是正式节点，仅回显关联的完成标记。',
  'Goal complete. The deleted source is not recreated.':
    '目标已完成，不会重新创建已删除的来源节点。',
  Plan: '计划',
  'Edit plan': '调整计划',
  'For later': '以后再做',
  'Waiting for prerequisite': '等待前置成果',
  'You can prepare this plan, but execution waits for the upstream delivery.':
    '可以先准备计划，执行需要等待上游成果验收完成。',
  'Context & delivery': '上下文与交付关联',
  'View retained source': '查看保留的来源',
  'Delivered input': '已交付的输入',
  'Delivery context becomes available after verification.':
    '验收完成后，实际交付成果将在这里作为输入提供。',
  'Retained source context': '保留的来源上下文',
  'Sample snapshot only. The real source graph is never changed.':
    '仅示例快照，不修改真实来源图。',
  'Source node deleted. This goal and its work are retained.':
    '来源节点已删除，本目标及其工作仍完整保留。',
  'Simulate source deletion': '模拟删除来源',
  'Shape the plan before you start': '先把路线聊清楚，再动手',
  'This plan is a prepared example, not an Agent response. Edit the upcoming steps and your requirements; verified work stays intact.':
    '这是预设演示计划，不是真实 Agent 回答。你可以调整后续步骤与补充要求，已验收成果保持不变。',
  'Your requirements': '你的补充要求',
  'Plan step': '计划步骤',
  'Save plan': '保存计划',
  'Confirm plan': '确认计划',
  'Capture a new idea without expanding this delivery. A blocker belongs to the current action, not here.':
    '记下临时想到的新需求，不扩大本次交付。阻塞问题应在当前步骤解决，不放进这里。',
  'New idea': '新的想法',
  Add: '添加',
  'No ideas parked here yet.': '暂时没有留待以后的想法。',
  'Current action': '当前步骤',
  'Ready to start': '准备开工',
  'Ready to verify': '等待验收',
  Verified: '已验收',
  Processing: '执行中',
  Verifying: '验证中',
  'Changes requested': '需要修正',
  'Ready to merge': '等待合并',
  'Needs your input': '需要补充信息',
  'Execution failed': '执行失败',
  'Plan to confirm': '计划待确认',
  'Agent is running': 'Agent 运行中',
  'Confirm the plan before starting an action.': '开始执行前，请先确认计划。',
  'Review plan': '查看计划',
  'Verify the earlier actions before starting this one.':
    '先验收前面的步骤，再开始这一步。',
  'Input & expected outcome': '输入与预期成果',
  'Expected output': '预期产出',
  Input: '输入',
  Process: '执行过程',
  Validation: '验收方式',
  'Simulating Agent review…': '正在模拟 Agent 审查…',
  'Simulating execution…': '正在模拟执行…',
  'You can leave this card. The result will return to this action.':
    '可以离开这张卡，结果会回到对应步骤。',
  'Cancel demo run': '取消演示运行',
  'The simulated process stopped unexpectedly. No new output was created; previous output is retained. Retry when ready.':
    '模拟进程意外退出，没有产生新版本，已有产出保留。准备好后可以重试。',
  'The Agent needs the supported runtime version before continuing. Add that information below and retry.':
    '继续之前需要明确支持的运行环境版本。请在下方补充信息后再试。',
  'This attempt was canceled. Existing output and feedback remain available.':
    '本次尝试已取消，已有产出和反馈仍然保留。',
  'Latest output': '最新产出',
  Round: '轮次',
  History: '历史',
  'Sample PR': '示例 PR',
  'Viewing earlier output. Verification and merge always target the latest round.':
    '正在阅读历史版本；验证和合并始终针对最新一轮。',
  Verification: '验证',
  'Review method': '审查方式',
  'Agent review': 'Agent 审查',
  'I will review': '我自己审查',
  'Completion condition: PR merged. A saved output or a positive review is not completion.':
    '完成条件：PR 已合并。保存产出或审查通过本身不代表完成。',
  'Blocking: focus is not restored after closing the dialog. Add a regression check before merging.':
    '阻塞意见：关闭对话框后没有恢复焦点。合并前需要修正并补充回归检查。',
  'These findings will accompany the next correction round. No correction starts automatically.':
    '这些意见会随下一轮修正一起带入，不会自动开始修改。',
  'Review passed. Waiting for your merge decision.':
    '审查通过，等待你决定是否合并。',
  'Simulate review': '模拟审查',
  'Simulate PR merged': '模拟 PR 已合并',
  'Demo rule: first-round review requests changes; review after a correction passes.':
    '演示规则：第一版审查会要求修正，修正后再次审查通过。',
  'Verified delivery': '交付已验收',
  'The sample PR is merged. This output can now support the next action.':
    '示例 PR 已合并，该成果现在可以支持下一步。',
  'Feedback for the next round': '下一轮的反馈',
  'Additional instructions': '补充说明',
  'Tell the Agent what to change or clarify…': '告诉 Agent 需要修改或澄清什么…',
  'Execution agent': '执行 Agent',
  'Simulate correction': '模拟修正',
  'Simulate execution': '模拟执行',
  'Demo scenario controls': '演示场景控制',
  'Next execution result': '下一次执行结果',
  'Return output': '返回产出',
  'Sample pull request': '示例 Pull Request',
  'Local illustration only. This PR does not exist on GitHub.':
    '仅本地演示，该 PR 并不存在于 GitHub。',
  Appearance: '外观',
  'Follow system': '跟随系统',
  Light: '浅色',
  Dark: '深色',
  'Choose a light or dark interface, or follow your system appearance.':
    '选择浅色或深色界面，也可以跟随系统外观。',
  '{agent} is running': '{agent} 运行中',
  'Show only {count} direct dependencies': '只显示 {count} 个直接依赖关系',
  'Show direct dependencies for {title}': '查看直接依赖：{title}',
  'In {inputs} · Out {outputs}': '输入 {inputs} · 输出 {outputs}',
  'Rev {revision} · In {inputs} · Out {outputs}':
    '版本 {revision} · 输入 {inputs} · 输出 {outputs}',
  '{agent} continues the same line of inquiry with only this round’s changes.':
    '{agent} 将沿当前方向继续，只补充本轮变化。',
  '{agent} responds with a Reflection and supported next directions.':
    '{agent} 将返回分析回应与有依据的下一步方向。',
  '{count} directions will be reconsidered together. No Formal Nodes will be changed.':
    '将一起重新考虑 {count} 个方向，不修改任何正式节点。',
  'Read previous output: {title}': '阅读上一轮输出：{title}',
  '{name} is always included': '始终带入 {name}',
  'Edit {id}': '编辑 {id}',
  'Decompose from {id}': '从 {id} 开始分解',
  'Send revision to {agent}': '向 {agent} 发送修订',
  'Send to {agent}': '发送给 {agent}',
  '{agent} runs locally with your existing subscription login.':
    '{agent} 使用你已有的订阅登录在本地运行。',
  'Existing child boundaries will not be replaced. Add new evidence or guidance so {agent} can propose only genuinely new siblings.':
    '已有子节点的边界不会被替换。补充新的资料或说明，让 {agent} 只提出真正新增的同级节点。',
  Continue: '继续',
  'Ready to close': '可以收尾',
  'Consider branching': '考虑新分支',
  Settings: '设置',
  General: '通用',
  Language: '语言',
  'Interface language': '界面语言',
  'Personal settings for this local Praxis installation.':
    '当前本地 Praxis 的个人设置。',
  'Only website menus, buttons, and messages change. Your input, Agent responses, Markdown, and JSON stay exactly as they are.':
    '只改变网站菜单、按钮和提示的显示语言。你的输入、Agent 回答、Markdown 和 JSON 均保持原样。',
  'Saved automatically on this computer.': '自动保存在这台电脑上。',
  'Saving…': '正在保存…',
  Saved: '已保存',
  'Could not save settings.': '无法保存设置。',
  'Back to projects': '返回项目列表',
  Overview: '概览',
  'Product context': '产品上下文',
  'Product Context is empty': '产品上下文暂时为空',
  'Formal documents will appear here as you use Product Discovery & Design, Scope Decomposition, Domain Modeling, Delivery Planning, and Implementation.':
    '使用产品探索与设计、范围分解、领域建模、交付规划和开发执行时，正式文档会自动出现在这里。',
  'Praxis collects accepted outputs here. Select a category and document to read the current formal context.':
    'Praxis 会自动汇总已接受的正式产物。选择分类和文档即可阅读当前上下文。',
  'Read {title} context': '阅读 {title} 上下文',
  'MVP Prototype': 'MVP 原型',
  'Product Design': '产品设计',
  Discovery: '探索',
  'Domain Model': '领域模型',
  'Task Breakdown': '任务分解',
  'Task Execution': '任务执行',
  'Accepted discovery outputs that define an early product slice.':
    '定义早期产品范围的已接受探索产物。',
  'Accepted product behavior and experience Features.':
    '已接受的产品行为与体验 Feature。',
  'The latest applied entities, fields, relationships, and rules.':
    '当前已应用的实体、字段、关系和规则。',
  'Accepted decomposition outputs with stable scope boundaries.':
    '具有稳定范围边界的已接受分解产物。',
  'Current formal delivery boundaries and their dependencies.':
    '当前正式交付边界及其依赖关系。',
  'Confirmed implementation plans and accepted Action outputs.':
    '已确认的实施计划和已接受的 Action 产物。',
  'Manually managed project resources.': '用户或 Agent 直接维护的项目资料。',
  "What's next": '下一步',
  Decomposition: '任务分解',
  'Break It Down': '拆开看',
  'Break It Down canvas': '拆开看画布',
  'Break It Down workspace': '拆开看工作区',
  'Just Do It': '动手做',
  Dependencies: '依赖关系',
  'Project navigation': '项目导航',
  'Switch project': '切换项目',
  Soon: '即将推出',
  Repository: '代码仓库',
  'Project workspace': '项目工作区',
  'Local only': '仅限本地',
  Projects: '项目',
  'Begin with a project boundary.': '从创建一个项目开始。',
  'Register a product idea or an existing code repository. Planning data stays beside the project while remaining invisible to its code history.':
    '创建一个产品想法，或关联已有代码仓库。规划数据保存在项目旁，不影响代码的提交历史。',
  'New project': '新建项目',
  'Create a project': '创建项目',
  'Choose where the project lives, then add only enough context to recognize it.':
    '选择项目位置，再填写名称和简短说明。',
  'Starting point': '起点',
  'Product idea': '产品想法',
  'No code repository yet': '还没有代码仓库',
  'Code repository': '代码仓库',
  'Attach existing local code': '关联已有本地代码',
  'Project name': '项目名称',
  Description: '简介',
  'Project directory': '项目目录',
  'Choose an existing local directory': '选择已有的本地目录',
  'A local-first workspace for one person building with agents.':
    '面向个人与 Agent 协作开发的本地工作区。',
  'Praxis creates a locally excluded .praxis directory inside this folder.':
    'Praxis 会在此文件夹内创建 .praxis 目录，并在本地排除其 Git 跟踪。',
  'Create the first project': '创建第一个项目',
  'Choose a folder, add a name, and write one short description.':
    '选择文件夹，填写名称和简短简介。',
  Choose: '选择',
  'Choosing…': '正在选择…',
  'Create project': '创建项目',
  'Creating…': '正在创建…',
  'Project overview': '项目概览',
  'No project description yet.': '尚未填写项目简介。',
  'Product sources': '产品资料',
  'Decomposition nodes': '分解节点',
  'Workspace ready': '工作区已就绪',
  'The project boundary is connected.': '项目目录已关联。',
  'Product context, decomposition, and dependency sync will be added as focused capabilities.':
    '在这里使用产品上下文、任务分解和依赖同步等功能。',
  'Next: product context': '下一步：产品上下文',
  'Add document': '添加文档',
  'Add feedback': '添加反馈',
  'Add or import a document for this folder.': '为此文件夹创建或导入文档。',
  'Add project-specific guidance and reference files that should be available whenever this feature asks an Agent to decompose work.':
    '添加项目专属说明和参考文件，供 Agent 分解任务时使用。',
  'Additional Context Library Resources': '补充上下文库资料',
  'Additional Local Markdown': '补充本地 Markdown',
  'Additional Resource folder': '补充资料文件夹',
  Ask: '提问',
  Assumptions: '假设',
  Attachments: '附件',
  'Break one scope into coherent, human-manageable nodes.':
    '把一个范围分解成连贯、便于理解的节点。',
  Cancel: '取消',
  'Collapse input panel': '折叠输入面板',
  'Cancel Agent Run': '取消 Agent 运行',
  Candidate: '候选',
  'Candidate · revision': '候选 · 版本',
  'Clear selected feedback text': '清除选中的反馈文本',
  'Clear the selection': '清除选择',
  Close: '关闭',
  'Close JSON preview': '关闭 JSON 预览',
  'Close Markdown reader': '关闭 Markdown 阅读器',
  'Close focus reading': '关闭专注阅读',
  Combine: '组合',
  'Compare with previous revision': '与上一版对比',
  Context: '上下文',
  'Context Library folder': '上下文库文件夹',
  'Context library': '上下文库',
  'Context sections': '上下文分类',
  'Create Start': '创建起点',
  'Create a flexible Product Context section. A README can be added later.':
    '创建产品上下文分类，之后可以添加 README。',
  'Create a readable Markdown file inside': '在此处创建 Markdown 文件：',
  'Create the fixed Product, Design, Engineering, Milestones, References, and Other folders with README guidance for people and agents.':
    '创建 Product、Design、Engineering、Milestones、References 和 Other 文件夹，并附上供人与 Agent 阅读的 README 说明。',
  Created: '创建时间',
  'Created through': '创建方式',
  'Decomposition canvas': '任务分解画布',
  'Decomposition instructions': '分解说明',
  'Decomposition workspace': '任务分解工作区',
  Delete: '删除',
  'Delete Markdown document': '删除 Markdown 文档',
  'Delete document': '删除文档',
  'Delete node': '删除节点',
  'Delete this card': '删除此卡片',
  Dependents: '被依赖于',
  'Depends on': '依赖于',
  'Derived from': '派生自',
  'Derived nodes': '派生节点',
  'Describe project-specific constraints, preferred resolution, naming conventions, acceptance expectations, or anything the Agent should account for while decomposing this scope.':
    '填写项目约束、期望粒度、命名规则、验收要求，以及 Agent 分解此范围时需要注意的事项。',
  'Describe what should change…': '描述需要修改的内容…',
  Discard: '丢弃',
  'Discard Candidate': '丢弃候选',
  'Discard this direction': '丢弃此方向',
  'Document title': '文档标题',
  Documents: '文档',
  'Drop Markdown files here, or browse': '拖入 Markdown 文件，或点击选择',
  'Drop Markdown or choose files': '拖入 Markdown 或选择文件',
  'Edit source': '编辑来源',
  'Edit start node': '编辑起点',
  'Every changed line is shown before this revision is accepted.':
    '接受此版本前，可以查看每一处行级变化。',
  'Explore more': '继续探索',
  'Expand input panel': '展开输入面板',
  'Expand Agent Run': '展开 Agent 运行状态',
  'Feedback for this Refine': '本次细化的反馈',
  Folder: '文件夹',
  'Folder name': '文件夹名称',
  'Focus current proposal': '聚焦当前提案',
  'Formal Nodes': '正式节点',
  'Graph canvas': '节点画布',
  'Graph details': '图关系详情',
  'Grew from': '来源节点',
  'Harness boundary': 'Harness 边界',
  'Hard dependencies': '硬依赖',
  'Import Markdown': '导入 Markdown',
  'Included automatically': '自动带入',
  'Inherited Resources': '继承的资料',
  'Inherited Resources stay on the source Node; additions apply only to this request.':
    '继承资料保留在来源节点上；新增资料仅用于本次请求。',
  'Initialize Product Context': '初始化产品上下文',
  'Inline feedback': '选区反馈',
  'Input from': '输入来源',
  Inputs: '输入',
  Instruction: '指令',
  'User Input': '用户输入',
  Instructions: '说明',
  'Latest Response': '最新回答',
  'Open full response': '查看完整回答',
  'Answer needed': '需要回答',
  Acceptance: '验收标准',
  Capability: '能力',
  'More evidence needed': '需要补充资料',
  Recommended: '推荐',
  'Choose an option or write your own answer in the Composer.':
    '可以选择一个建议，也可以在右侧自由回答。',
  'Updated {elapsed} ago': '{elapsed} 前更新',
  'Key Rules': '关键规则',
  'No change': '无需修改',
  No: '否',
  Lineage: '派生关系',
  Lines: '行',
  'Local Markdown': '本地 Markdown',
  'Markdown and JSON references owned by this feature context.':
    '此功能上下文使用的 Markdown 和 JSON 参考资料。',
  'Markdown or JSON · 2 MB each': 'Markdown 或 JSON · 每个文件最多 2 MB',
  Metadata: '元数据',
  'New Folder': '新建文件夹',
  'New Markdown': '新建 Markdown',
  'New Markdown document': '新建 Markdown 文档',
  'New context folder': '新建上下文文件夹',
  'No Markdown documents': '没有 Markdown 文档',
  'No Markdown documents are available yet.': '尚无可用的 Markdown 文档。',
  'No attachments yet. Instructions can be used on their own.':
    '尚无附件，也可以只填写说明。',
  'No active proposal': '暂无当前提案',
  None: '无',
  'Open details': '打开详情',
  'Optional Resources for this Agent Run only':
    '可选资料，仅用于本次 Agent 运行',
  'Optional sources': '可选资料',
  'Only Markdown Resources can be added right now.':
    '目前只能添加 Markdown 资料。',
  'Out Of Scope': '范围外',
  Outputs: '输出',
  'Previous User Input': '上一轮用户输入',
  'Previous outputs ·': '上一轮输出 ·',
  'Previous proposal': '上一轮提案',
  'Previous proposal context': '上一轮提案上下文',
  'Proposal workspace status': '提案工作区状态',
  'Current Candidates': '当前候选',
  'Module Depends On': '模块依赖',
  'Read full last response': '阅读上一轮完整回答',
  'Redo proposal': '重做整轮提案',
  'Referenced by': '被引用于',
  Refine: '细化',
  'Refine this Markdown': '细化此 Markdown',
  Relationships: '关系',
  'Remove Resource': '移除资料',
  'Remove attachment': '移除附件',
  'Remove context attachment?': '移除此上下文附件？',
  'Remove inline feedback': '移除此反馈',
  'Remove source': '移除来源',
  'Rename context folder': '重命名上下文文件夹',
  'Rename folder': '重命名文件夹',
  'Rename the folder on disk without changing its documents.':
    '重命名磁盘上的文件夹，不改变其中的文档。',
  'Replace existing documents?': '覆盖已有文档？',
  Resources: '资料',
  Review: '审阅',
  Revise: '修订',
  Revision: '版本',
  'Revision note': '修订说明',
  Role: '角色',
  'Run-only context': '本次补充上下文',
  Save: '保存',
  'Select a section to read its purpose and Agent loading guidance. The folder structure is the source of truth.':
    '选择分类以阅读用途和 Agent 加载说明。文件夹结构即为实际结构。',
  'Select every document needed to understand what will be decomposed.':
    '选择理解此次分解范围所需的所有文档。',
  'Selected dependencies': '选中节点的依赖',
  'Selected text feedback': '选中文本反馈',
  'Show README folder in file manager': '在文件管理器中显示 README 文件夹',
  'Show in file manager': '在文件管理器中打开',
  'Source Markdown': '来源 Markdown',
  'Source proposal': '来源提案',
  'Stable ID': '稳定标识',
  Start: '起点',
  'Start and ask': '创建起点并提问',
  'Start-node title': '起点标题',
  Status: '状态',
  'The folder path uses an English slug.': '文件夹路径使用英文短名称。',
  'The name becomes an English slug such as research-notes.':
    '名称会转换为 research-notes 这样的英文短名称。',
  'The next revision is running.': '正在生成下一版。',
  'The title becomes an English slug such as product-foundation.md.':
    '标题会转换为 product-foundation.md 这样的英文文件名。',
  'Their output becomes the input for one question.':
    '这些节点的输出将作为一次提问的输入。',
  'This Candidate and its output will move to the operating system Trash. Other Candidates from the same proposal stay unchanged.':
    '此候选及其输出会移到系统回收站，同轮其他候选保持不变。',
  'This Node carries no Resources yet.': '此节点尚未附带资料。',
  'This folder has no Markdown documents.': '此文件夹没有 Markdown 文档。',
  'This folder is empty.': '此文件夹为空。',
  'This project has no Product Context library yet.':
    '此项目尚未建立产品上下文库。',
  Type: '类型',
  'Up to 20 files, 2 MB each': '最多 20 个文件，每个不超过 2 MB',
  Updated: '更新时间',
  Yes: '是',
  'User-owned constraints and preferences. The feature Harness is separate and will not overwrite this file.':
    '由你管理的约束和偏好。功能 Harness 独立维护，不会覆盖此文件。',
  'What do you want to build?': '你想做一个什么样的产品？',
  'What do you want to break down?': '你想拆解什么？',
  'Describe the scope in your own words. It becomes the Canvas Start and the first Agent instruction.':
    '用自己的话描述范围。它会成为画布起点和发给 Agent 的第一条指令。',
  'Decomposition purpose': '拆解目的',
  Adjustment: '调整方式',
  'Replace the selected unaccepted Candidate working set atomically. Accepted Nodes remain unchanged.':
    '原子重组所选的未接受候选工作集，已接受节点保持不变。',
  'Recompose outputs belong to one atomic working set and cannot be discarded individually.':
    '重组结果属于同一个原子工作集，不能单独丢弃。',
  'Describe how these Candidates should be retained, replaced, split, merged, added or removed.':
    '说明这些候选应如何保留、替换、拆分、合并、新增或移除。',
  'Accept these prerequisites first': '请先接受这些前置候选',
  'Pending acceptance': '待接受',
  Stabilized: '已稳定',
  'Exploration purpose': '探索目的',
  'Understand the structure': '理清结构',
  'Form coherent sibling boundaries at a human-manageable resolution.':
    '在适合人理解和管理的粒度上形成清晰的同级边界。',
  'Product modules': '产品模块',
  'Identify product capabilities with clear included and excluded behavior.':
    '按照产品能力拆分，并明确包含与不包含的行为。',
  'Implementation approach': '实现方案',
  'Partition technical responsibility, data flow and integration boundaries.':
    '拆分技术职责、数据流和集成边界。',
  'Delivery breakdown': '交付拆分',
  'Create implementation-ready deliverables with acceptance and validation evidence.':
    '形成可直接实现、具有验收与验证证据的交付项。',
  'Explore concrete product value and testable user experiences.':
    '探索具体的产品价值和可验证的用户体验。',
  'Synthesize selected Discovery evidence into Product Design Features.':
    '把选中的 Discovery 证据提炼为 Product Design Feature。',
  'Complete a known product with justified missing Feature boundaries.':
    '根据已有产品定义补全有充分依据的 Feature 边界。',
  'A product, feature or technical scope that should become coherent boundaries…':
    '一个需要整理成清晰边界的产品、功能或技术范围…',
  'Decomposition scope': '拆解范围',
  'Start and decompose': '创建起点并拆解',
  'What do you want to do with these together?': '你想如何一起使用这些内容？',
  'Describe the result you want from these cards.':
    '说明你希望这些卡片生成什么结果。',
  'What should the Agent reconsider here?': '你希望 Agent 重新考虑什么？',
  'What to do with the selected cards': '对选中卡片的要求',
  'Product Design Completion': '产品设计补全',
  'MVP Exploration': 'MVP 探索',
  'Feature Synthesis': '功能提炼',
  Intention: '探索目的',
  Motion: '调整方式',
  Unspecified: '未指定',
  Diverge: '发散',
  Converge: '收敛',
  'The Product Source and all current Product Design Features are included automatically.':
    '系统会自动带入 Product Source 和当前所有 Product Design Feature。',
  'Edit feedback': '编辑反馈',
  'Save feedback': '保存反馈',
  'Delete feedback': '删除反馈',
  'Your idea': '你的想法',
  'always included': '始终带入',
  attached: '已附加',
  cards: '张卡片',
  'is working…': '正在工作…',
  more: '更多',
  selected: '已选择',
  '· revision': '· 版本',
  '· unaccepted direction': '· 未接受的方向',
  Accept: '接受',
  'Accepting…': '正在接受…',
  'Starting…': '正在启动…',
  'Start exploration': '开始探索',
  'Continue exploration': '继续探索',
  'Continue from': '继续探索自',
  'Explore from': '探索自',
  'Redo proposal from': '重做提案自',
  'Re-propose': '重新提案',
  Correction: '纠正说明',
  required: '必填',
  optional: '可选',
  'What did this proposal misunderstand, and what do you want instead?':
    '上一轮提案误解了什么？你实际想要什么？',
  'Steer this round, or let the Agent respond from the current Node.':
    '填写本轮要求，或让 Agent 从当前节点继续。',
  'Save changes': '保存修改',
  'Creating project…': '正在创建项目…',
  Edit: '编辑',
  'Choose files': '选择文件',
  Remove: '移除',
  Rename: '重命名',
  'Renaming…': '正在重命名…',
  Import: '导入',
  'Importing…': '正在导入…',
  'Deleting…': '正在删除…',
  Running: '运行中',
  Failed: '失败',
  Canceled: '已取消',
  Source: '来源',
  Preview: '预览',
  'Send Refine': '发送细化请求',
  Refining: '正在细化',
  'Close reader': '关闭阅读器',
  'Enable annotations': '开启标注',
  'Disable annotations': '关闭标注',
  'Open focus reading': '开启专注阅读',
  'Exit focus reading': '退出专注阅读',
  'Open focus mode': '开启专注模式',
  'Exit focus mode (Esc)': '退出专注模式（Esc）',
  'Zoom In': '放大',
  'Zoom Out': '缩小',
  'Fit View': '适应画布',
  'Project settings': '项目设置',
  'Accept revision': '接受此版本',
  'Add to selection': '加入选择',
  'Adding…': '正在添加…',
  'Context ready': '上下文已就绪',
  'Create context structure': '创建上下文结构',
  'Create document': '创建文档',
  'Create fixture request': '创建演示请求',
  'Create folder': '创建文件夹',
  'Create start node': '创建起点',
  Decompose: '分解',
  'Define this round of work. Inherited Resources stay on the source Node; additions apply only to this request.':
    '填写本轮任务要求。继承资料保留在来源节点上，新增资料仅用于本次请求。',
  'Delete the referencing cards first': '请先删除引用此卡片的节点',
  'Delete the referencing nodes first': '请先删除引用此节点的其他节点',
  'Describe how this Candidate itself should change.':
    '描述这张候选卡本身需要怎样调整。',
  'Describe the new evidence or boundary that may require additional siblings.':
    '说明可能需要新增同级节点的补充资料或边界。',
  'Development fixture only. Nothing is sent to an Agent.':
    '仅为开发演示，不会向 Agent 发送请求。',
  'Discarding…': '正在丢弃…',
  'Drop files or choose attachments': '拖入文件或选择附件',
  'Explore more adds directions without replacing the current proposal.':
    '继续探索会新增方向，不替换当前提案。',
  'Find additional nodes': '寻找补充节点',
  'Recompose working set': '重组工作集',
  'Initializing…': '正在初始化…',
  'Manual creation': '手动创建',
  'Move node to Trash': '将节点移到回收站',
  'Move this card to Trash': '将卡片移到回收站',
  'New start node': '新建起点',
  'No description yet.': '尚无说明。',
  'No User Input was recorded for this proposal.':
    '此提案没有记录上一轮用户输入。',
  'Not configured': '尚未配置',
  Nothing: '无',
  'Open output.md': '打开 output.md',
  'Opening output…': '正在打开输出…',
  'Opening…': '正在打开…',
  'Preview only': '仅供预览',
  'Re-propose discards the current directions to system Trash and immediately generates a new proposal. Cancellation or failure does not restore discarded directions.':
    '重新提案会把当前方案移到系统回收站，并立即生成新提案。取消或失败都不会恢复已丢弃的方案。',
  'Redefine this Candidate only. Revisions cannot create siblings or child Nodes.':
    '只重新定义这张候选卡，不创建同级节点或子节点。',
  'Redo all unaccepted directions from this parent':
    '重做此父节点下所有尚未接受的方向',
  'Removing…': '正在移除…',
  Replace: '覆盖',
  'Replacing…': '正在覆盖…',
  'Save instructions': '保存说明',
  'The node folder will move to the operating system Trash. Its upstream relationships will disappear with it.':
    '节点文件夹会移到系统回收站，它与上游节点的关系也会移除。',
  'This removes the node from the development preview until the page reloads.':
    '从开发预览中移除此节点，刷新页面后恢复。',
  Unselect: '取消选择',
  'A manager that helps one developer grow and decompose product intent…':
    '一个帮助个人开发者逐步完善想法并分解产品内容的工具…',
  'Praxis’s feature-level generation contract will be designed separately. It will consume this user context but remain independently versioned and replaceable.':
    'Praxis 的功能生成契约独立设计。它会读取这些用户上下文，但独立维护版本，可单独替换。',
  'What&apos;s next': '下一步',
  "What's Next": '下一步',
  'Write the idea in your own words. It becomes the Start of this Canvas, and':
    '用自己的话描述想法。它会成为画布的起点，由',
  'answers it straight away.': '直接回答。',
  '. Delete those first.': '。请先删除它们。',
  '. Select them above and delete them first.': '。请先在上方选择并删除它们。',
  '. Existing directions and dependencies remain unchanged.':
    '。现有方向和依赖关系保持不变。',
  '/ 100,000 characters': '/ 100,000 字符',
  'A captured': '已记录的',
  'This removes the Markdown file from the project. The':
    '这会移除项目中的 Markdown 文件，但',
  'folder will remain.': '文件夹会保留。',
  'This rewrites the Markdown carried by': '这会改写以下节点中的 Markdown：',
  'node and its fixed source boundary.': '节点及其固定的来源边界。',
  already: '已经存在',
  'in this folder. Importing will replace the existing':
    '在此文件夹中。导入会覆盖已有的',
  'will be deleted from this project’s Decomposition context folder.':
    '将从此项目的任务分解上下文文件夹中删除。',
  'Revision {revision} · {count} Resources': '版本 {revision} · {count} 份资料',
  'Open details for {title}': '打开详情：{title}',
  'What to Do': '做什么',
  'Open in What to Do': '在“做什么”中打开',
  'Open in Just Do It': '在“动手做”中打开',
  'Turn accepted Product Design into deliverable Contracts.':
    '把已接受的产品设计整理成可交付的 Contract。',
  'Prepare a Delivery Map': '规划交付地图',
  'Choose accepted Product Design, then describe what should be delivered.':
    '选择已接受的产品设计，再描述本次希望交付的结果。',
  'Describe the update. Add Features or focus Contracts when useful.':
    '描述这次希望怎样更新；需要时可以添加 Feature 或选择重点 Contract。',
  'Product Design Features': '产品设计 Feature',
  'Main Context': '主要上下文',
  'Add Feature': '添加 Feature',
  'Remove {title}': '移除「{title}」',
  'Add Product Design Feature': '添加产品设计 Feature',
  'Choose accepted Product Design Features as the Main Context for this Delivery Map.':
    '选择已接受的产品设计 Feature，作为本轮交付地图的主要上下文。',
  'Add at least one accepted Feature as Main Context.':
    '请添加至少一个已接受的 Feature 作为主要上下文。',
  'Add a Feature only when this update needs new Product Design context.':
    '只有这次更新需要新的产品设计上下文时，才需要添加 Feature。',
  'Product Design Feature': '产品设计 Feature',
  'Product Source': '产品源',
  'Add selected Features': '添加所选 Feature',
  'Accept a Product Design Feature in What’s Next before creating a Delivery Map.':
    '请先在下一步中接受至少一个产品设计 Feature，再创建交付地图。',
  'Describe the delivery outcome, constraints or priorities…':
    '描述交付结果、限制条件或优先级…',
  'Extra info': '补充资料',
  'Create Delivery Map': '创建交付地图',
  'Update Delivery Map': '更新交付地图',
  'Default Context': '默认上下文',
  'Current Delivery Map · {count} Contracts':
    '当前交付地图 · {count} 个 Contract',
  'Focused Contracts': '重点 Contract',
  'Could not start the Agent Run.': '无法启动 Agent Run。',
  'Could not restore the failed Run.': '无法恢复失败运行的输入。',
  'The What to Do Agent Run failed.': 'What to Do Agent Run 失败。',
  'The Agent Run was canceled. The Delivery Map was not changed.':
    'Agent Run 已取消，交付地图没有改变。',
  'Proposed {count} Delivery Contracts for review.':
    '已生成 {count} 个 Delivery Contract，等待查看。',
  'The Delivery Map is ready for review.': '交付地图已经生成，可以查看。',
  'The Delivery Map was updated.': '交付地图已更新。',
  Applied: '已应用',
  Response: '回答',
  Summary: '摘要',
  Log: '日志',
  'Activity Log': '活动日志',
  'Copy link': '复制链接',
  'Action {current}/{total}': 'Action {current}/{total}',
  Accepted: '已通过',
  '{count} additional findings': '{count} 条附加发现',
  'Collapse Latest Response': '收起最新回答',
  'Link copied': '已复制链接',
  Project: '项目',
  Module: '模块',
  Owner: '所属',
  Subject: '主题',
  'Run ID': 'Run ID',
  'Operation ID': '操作 ID',
  'Job ID': 'Job ID',
  'Agent profile': 'Agent 配置',
  Started: '开始',
  Ended: '结束',
  Duration: '耗时',
  Warning: '警告',
  Fail: '失败',
  Stopping: '正在停止',
  'Job log': 'Job 日志',
  checkpoint: '检查点',
  'Retained: {files} modified files, {commits} commits, {prs} pull requests':
    '已保留：{files} 个修改文件、{commits} 个 commit、{prs} 个 pull request',
  'This Run predates Run Logs; its recorded activity is shown in the same format.':
    '这个 Run 早于 Run Log 机制；这里以相同格式显示它记录的活动。',
  'Delivery Contract': '交付 Contract',
  'Preparing Delivery Map': '正在规划交付地图',
  'Agent Run': 'Agent Run',
  'Reading the frozen Packet and coordinating Contracts.':
    '正在读取冻结的 Packet，并协调各个 Contract。',
  "Ask what's next": '探索下一步',
  '{action} from {title}': '从「{title}」{action}',
  'Add feedback for lines {start} to {end}': '为第 {start} 至 {end} 行添加反馈',
};

export function translateUi(
  language: UiLanguage,
  text: string,
  values: Record<string, string | number> = {},
) {
  const message = language === 'zh-CN' ? (chineseUi[text] ?? text) : text;
  return message.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : match,
  );
}
