import type { ProductExplorationCandidateRecord } from './contract.ts';
import {
  assertLatestPendingSelection,
  latestPendingCandidates,
  readIdentifiedProposalRuns,
  visibleProposalRuns,
  candidateRevision,
  assertExpectedRevision,
  CandidateAcceptanceError,
  type AcceptCandidateOptions,
  type PendingCandidateProjection,
  type StoredCandidateDocument,
} from '../../graph/proposal/pending.ts';
import {
  revisionRunInProgress,
  withModuleMutation,
} from '../../graph/proposal/module-runtime.ts';
import { promoteCandidateToNode } from '../../graph/proposal/promote.ts';
import { stageCandidateDocuments } from '../../graph/proposal/stage.ts';
import type { RegisteredProject } from '../../project-registry.ts';
import {
  collectAcceptedCandidateIds,
  productExplorationRunsDirectory,
  PRODUCT_EXPLORATION_GRAPH_ROOT,
} from './assembly.ts';
import path from 'node:path';

const MUTATION_KEY = 'whatsNextMutations' as const;
const RUN_REGISTRY_KEY = '__praxisWhatsNextRuns' as const;
const DEFAULT_LAYER = 'discovery';
const DEFAULT_ARTIFACT_KIND = 'direction';

export function renderLegacyCandidateMarkdown(candidate: {
  title: string;
  summary: string;
  assumptions?: string[];
}) {
  const assumptions = candidate.assumptions?.length
    ? candidate.assumptions.map((assumption) => `- ${assumption}`).join('\n')
    : '- None';
  return `# ${candidate.title}

${candidate.summary}

## Why this direction

- This direction was generated by the legacy What's Next Harness.
- Review its original Run evidence before accepting or refining it.

## Assumptions

${assumptions}`;
}

async function readVisibleProposalRuns(project: RegisteredProject) {
  return visibleProposalRuns(
    await readIdentifiedProposalRuns(
      project.planningPath,
      PRODUCT_EXPLORATION_GRAPH_ROOT,
      productExplorationRunsDirectory(project),
    ),
  );
}

function acceptanceEligibility(candidate: StoredCandidateDocument) {
  if (!candidate.uid || !candidate.relations)
    return {
      acceptable: false,
      reason: 'This Candidate has no stable identity yet.',
    };
  if (revisionRunInProgress(RUN_REGISTRY_KEY, candidate.candidateId!))
    return {
      acceptable: false,
      reason: 'A Candidate revision Run is still active.',
    };
  return { acceptable: true, reason: null };
}

export async function listPendingProductExplorationCandidates(
  project: RegisteredProject,
): Promise<PendingCandidateProjection[]> {
  const accepted = new Set(await collectAcceptedCandidateIds(project));
  return latestPendingCandidates(
    await readVisibleProposalRuns(project),
    accepted,
  ).map(({ runId, candidate }) => ({
    runId,
    candidateId: candidate.candidateId!,
    revision: candidateRevision(candidate),
    uid: candidate.uid ?? null,
    type: candidate.type ?? '',
    title: candidate.title ?? '',
    summary: candidate.summary ?? '',
    layer: candidate.layer ?? DEFAULT_LAYER,
    artifactKind: candidate.artifactKind ?? DEFAULT_ARTIFACT_KIND,
    derivedFrom: candidate.derivedFrom ?? [],
    dependsOn: candidate.dependsOn ?? [],
    acceptance: acceptanceEligibility(candidate),
  }));
}

export async function acceptProductExplorationCandidate(
  project: RegisteredProject,
  runId: string,
  candidateId: string,
  options: AcceptCandidateOptions = {},
) {
  return withModuleMutation(MUTATION_KEY, project.planningPath, () =>
    acceptProductExplorationCandidateUnlocked(
      project,
      runId,
      candidateId,
      options,
    ),
  );
}

async function acceptProductExplorationCandidateUnlocked(
  project: RegisteredProject,
  runId: string,
  candidateId: string,
  options: AcceptCandidateOptions,
) {
  const runs = await readVisibleProposalRuns(project);
  const run = runs.find((stored) => stored.runId === runId);
  if (!run)
    throw new CandidateAcceptanceError(
      'proposal-unavailable',
      'The Candidate proposal is no longer available.',
      400,
    );
  if (revisionRunInProgress(RUN_REGISTRY_KEY, candidateId))
    throw new CandidateAcceptanceError(
      'active-revision',
      'Wait for the active Candidate revision to finish.',
      400,
    );
  if (run.result?.outcome !== 'proposal')
    throw new CandidateAcceptanceError(
      'proposal-unavailable',
      'The Candidate proposal is unavailable.',
      400,
    );
  const candidate = (run.result.candidates ?? []).find(
    (value) => value.candidateId === candidateId,
  );
  if (!candidate)
    throw new CandidateAcceptanceError(
      'candidate-not-found',
      'The Candidate could not be found.',
      400,
    );
  assertExpectedRevision(candidate, options.expectedRevision);
  assertLatestPendingSelection(
    latestPendingCandidates(
      runs,
      new Set(await collectAcceptedCandidateIds(project)),
    ),
    { runId, candidateId, revision: candidateRevision(candidate) },
  );
  if (!candidate.uid || !candidate.relations)
    throw new CandidateAcceptanceError(
      'no-stable-identity',
      'The Candidate has no stable identity.',
      409,
    );

  await stageCandidateDocuments(
    path.join(
      project.planningPath,
      PRODUCT_EXPLORATION_GRAPH_ROOT,
      'runs',
      runId,
    ),
    [
      {
        candidateId,
        markdown:
          candidate.outputMarkdown ??
          renderLegacyCandidateMarkdown({
            title: candidate.title ?? candidateId,
            summary: candidate.summary ?? '',
            assumptions: candidate.assumptions,
          }),
      },
    ],
  );

  return promoteCandidateToNode(project, {
    scope: PRODUCT_EXPLORATION_GRAPH_ROOT,
    runId,
    candidate: {
      ...(candidate as ProductExplorationCandidateRecord),
      uid: candidate.uid,
      relations: candidate.relations,
    },
    extension: {
      layer: (candidate.layer ?? DEFAULT_LAYER) as never,
      artifactKind: (candidate.artifactKind ?? DEFAULT_ARTIFACT_KIND) as never,
    },
    provenanceFeature: 'whats-next',
  });
}

export async function findPendingProductExplorationCandidate(
  project: RegisteredProject,
  candidateId: string,
) {
  const accepted = new Set(await collectAcceptedCandidateIds(project));
  return (
    latestPendingCandidates(
      await readVisibleProposalRuns(project),
      accepted,
    ).find((entry) => entry.candidate.candidateId === candidateId) ?? null
  );
}
